version: '3.8'

services:
  gradio-fastapi-django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio-fastapi-django-main
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.groq.com/openai/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-llama3-8b-8192}
      - LOCAL_MODEL=${LOCAL_MODEL:-true}
      - GOOGLE_APPLICATION_CREDENTIALS_CONTENT=${GOOGLE_APPLICATION_CREDENTIALS_CONTENT}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
    volumes:
      - ./cache:/app/cache
      - ./gradio_cached_examples:/app/gradio_cached_examples
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - gradio-network

networks:
  gradio-network:
    driver: bridge
